# Generated by Django 5.2 on 2025-04-18 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('TITLE_DEED', 'Title Deed'), ('SURVEY_PLAN', 'Survey Plan'), ('ID_PROOF', 'Identity Proof'), ('TAX_RECEIPT', 'Tax Receipt'), ('OTHER', 'Other')], max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ipfs_hash', models.CharField(max_length=100)),
                ('blockchain_reference', models.CharField(max_length=256)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='land_registry.landparcel')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
