# Generated by Django 5.2 on 2025-04-18 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coordinates', models.JSONField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('blockchain_hash', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Verification'), ('DISPUTED', 'Under Dispute'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='LandTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_hash', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('documents', models.JSONField(blank=True, null=True)),
                ('from_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_sold', to=settings.AUTH_USER_MODEL)),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='land_registry.landparcel')),
                ('to_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_purchased', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
